import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import 'lenis/dist/lenis.css';

import { NavProvider } from '@/components/context/nav-context';
import { InitProvider } from '@/components/context/init-context';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <InitProvider>
        <NavProvider>
          <body className={inter.className}>{children}</body>
        </NavProvider>
      </InitProvider>
    </html>
  );
}
